### ISSUE TITLE
trowaSoft v0.5.5.2 - voltSeq: early first step isn't played (or partially played) on RST

### ISSUE THREAD

**Issue by DomiKamu** [j4s0n-c/trowaSoft-VCV#11]
trowaSoft v0.5.5.2.
Windows 7 Pro SP1 x64 (also 10), VCV Rack v0.5.1

Hi Jason,

I report an issue (I've already discovered in previous v0.5.5.1) about voltSeq, lastest v0.5.5.2, VCV

In particular when voltSeq is stopped, then "RST", then "RUN", the early first step is not played (or played too quick, regardling next notes). On next loops however, the first steps (notes) are correctly played however (I mean: at same speed).

EDIT: the culprit seems to be the RESET (button or via RST input) when seq is running, I presume a "timer" doesn't restart at beginning.

Note: VCV Rack audio engine is set at 44100 Hz (like my Saffire Pro 14 ASIO interface).

Regards.

Dominique

**Comment by chichian** [comment]
Oops. We'll look into it. I thought I had worked on that before but maybe that was only for trigSeq.

**Comment by DomiKamu** [comment]
Don't worry! your trowaSoft modules are simply fabulous (I'm experiment OSC together with Lemur on iOS), you'll can fix it for future release (perhaps against VCV Rack v0.6.0), so be sure it's not urgent. I'm considering we're into a fantastic community, and we can help us together as soon as it's possible, it's my state of mind (I've lot of free time b'coz I'm unemployed).

Greetings from Chartres, France.
Dominique.

**Comment by j4s0n-c** [comment]
This happens because the reset occurs immediately instead of waiting for the next step to keep the timing "on the grid". We will correct this ASAP.

**Comment by j4s0n-c** [comment]
@DomiKamu Have you tried the update to see if this issue can be closed?

**Comment by DomiKamu** [comment]
Hi Jason, I've tested yet (voltSeq v0.6.1), of course fixed, I close this issue. Thanks a lot!
