### ISSUE TITLE
Bug: TrigSeq64 

### ISSUE THREAD

**Issue by Coirt** [j4s0n-c/trowaSoft-VCV#12]
The last drag on TrigSeq64 gets copied to channels 2-16 when you change to that channel. 
![seq64](https://user-images.githubusercontent.com/12150421/36413416-3697c1aa-1616-11e8-98b5-9a9b5b1066c1.gif)
Also happens when drag start from channel 16 then select channel 15 downwards. 
Might be the same on the 16 have not checked.

Suggestion also. If you have a pattern that is steps 1 and 4 then 16 and 20. When you drag start, step 1 the other steps not activated activate it would be greet if on drag it could detect the steps that are true only, The ones that are active then turn those off without turning the ones that are off on. 

This is what I mean:
![is on true](https://user-images.githubusercontent.com/12150421/36413859-0bc0d744-1618-11e8-8fd3-9be108b6eedf.gif)

**Comment by chichian** [comment]
Oops. I noticed that happened when I first did it, but I thought I had adjusted it to fix that. Let me look at that again, I probably broke it.

**Comment by chichian** [comment]
Hi Coirt,

The bug **should** be fixed in the new [0.6 release](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v0.6.0).  Let me know if you notice any more issues with it. 

Thanks!

**Comment by j4s0n-c** [comment]
Issue resolved with latest update.
