### ISSUE TITLE
Help upgrading to v0.6?

### ISSUE THREAD

**Issue by cschol** [j4s0n-c/trowaSoft-VCV#16]
Hi,

do you need any help from the [Rack Plugin Repair Team](https://github.com/VCVRack/community/issues/269) upgrading your plugins to `v0.6` or are you planning on doing the work yourself?

**Comment by chichian** [comment]
Hi cschol,

We've already started upgrading. Thanks. 

When is 0.60 planned for release?

**Comment by cschol** [comment]
March 21 was last I heard.

**Comment by phdsg** [comment]
on macOS/linux: getting a linker error at the end of `make` complaining about rtmidi...
```
ld: library not found for -lrtmidi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [plugin.dylib] Error 1
make: *** [allplugins] Error 2
```

```
/usr/bin/ld: cannot find -lrtmidi
collect2: error: ld returned 1 exit status
../../compile.mk:46: recipe for target 'plugin.so' failed
make[1]: *** [plugin.so] Error 1
```

**Comment by cschol** [comment]
@chichian The `Makefile` should be updated to the latest template. You don't need to set `LDFLAGS` for Rack provided libraries, which in this case causes link issues. The `Makefile` framework will take care of that for you. It gets much simpler with the new template, for example the `dist` target is gone. Look at [Fundamental Makefile](https://github.com/VCVRack/Fundamental/blob/master/Makefile) for an example.

**Comment by j4s0n-c** [comment]
Oops. sorry. I've updated the file. I have tried to make it as much like Fundamental's as possible. I think I've cleaned it up as much as I can in Windows anyway.  

I can check the other OS's in the next few days. If someone else could check sooner and report any other issues that would be awesome.

**Comment by j4s0n-c** [comment]
Oops. This comment and the ^^^ omment above is really from @chichian. Sorry, using j4s0n's computer.

**Comment by cschol** [comment]
All good on Windows and Linux. @phdsg will test on Mac. Thanks @chichian for fixing!
