### ISSUE TITLE
Possible bug in reset of Volt seq, possibly caused by seq 64

### ISSUE THREAD

**Issue by a1laserboy** [j4s0n-c/trowaSoft-VCV#2]
Hi, while playing, I think either I am doing something wrong or maybe found a little bug in volt seq. I've attached the patch. 

I'm using the top volt seq to play the bass, and then seq 64 to trigger the bottom volt seq to transpose the bass.

It's to do with resetting. When I hit reset, the top one that triggers directly from the clock is fine, but the bottom one that triggers from seq 64 triggers both first steps on reset. 

Upon further testing, slowing the clock right down doesn't cause the issue in the top one still, but is still there in the one triggered by seq 64. I'm starting to think it's maybe seq 64 actually now.

[I Feel Love.vcv.zip](https://github.com/j4s0n-c/trowaSoft-VCV/files/1569787/I.Feel.Love.vcv.zip)

**Comment by j4s0n-c** [comment]
I modified the patch to have the reset trigger be step one on ch 2 of the trigSeq so the voltseq doesn't get the double trigger on reset of everything else. I also tuned up the oscillator a bit so I could hear it. Let us know if this is the result you were expecting.

[I Feel Love_Fixed.vcv.zip](https://github.com/j4s0n-c/trowaSoft-VCV/files/1573260/I.Feel.Love_Fixed.vcv.zip)

**Comment by a1laserboy** [comment]
Thanks :)

Its interesting why taking the pulse from ch2 works over the reset from the clock. I wonder if the pulse from the clock is too long or short, or if the two pulses being out of time (first from reset and then from seq64) could be the problem. I know each module adds 1ms.

Sorry about the low pitch, it is a bassline, but of course, this is more about the operation than the notes :)

**Comment by j4s0n-c** [comment]
When reset, the value of the first step is output (on all the sequencers). So the voltSeq was getting reset to step 1 by the clock, then getting the first pulse from the trigSeq to step 2 almost simultaneously. Now the reset to step one is technically happening after the main reset and first clock pulse, so it should work even if you turned off step one of the trigSeq ch1.
