### ISSUE TITLE
Notes in voltage

### ISSUE THREAD

**Issue by soyva3** [j4s0n-c/trowaSoft-VCV#20]
Is there a fast way to reset everything to 0 or is not a best practice to start notation in 0, I spend a lot of time from -10 to 0 (not as much as you developing this awesome tool of course) 👍

**Comment by chichian** [comment]
Hi Amindamaru, 

In the latest version (for Rack v0.6), voltSeq should default to 0 V (C4).  I think the new Rack should be out soon or you can compile from the latest source if you have the 0.6 dev version of Rack.
