### ISSUE TITLE
voltSeq (0.6.0) lastest 16th step init issues

### ISSUE THREAD

**Issue by DomiKamu** [j4s0n-c/trowaSoft-VCV#21]
Hi,

I'm testing voltSeq for Rack 0.6.0.
Windows platform.

It seems an initialization problem when you add voltSeq in rack, concerning the last 16th step.

At start, it's voltage is 0.0, assuming it's good.

But now, when you switch to "Note" mode, this 16th step is set to "C-1" (instead of default "C4" - like other steps are), Show in attached screen capture.

Now switching to "Patt" mode, pattern number is also different (01) than other steps (all are 33). And finally when you'll switch back to "Volt" mode, the 16th have changed from 0.0 to -10.0.

Hope mine explanations are clear (English isn't my main language).

Regards.
Dominique

![bug voltseq](https://user-images.githubusercontent.com/24851960/38113573-aff79e9c-33a5-11e8-9043-572000c2afa7.png)

**Comment by DomiKamu** [comment]
Sometimes, Initialize over module via context menu (or Ctrl+I / Command+I) also having a wrong behavior about 16th step....

**Comment by chichian** [comment]
Oh, that's not good.  I will look into it. Thanks for reporting.

By the way, your English is great!

**Comment by j4s0n-c** [comment]
Copied from another unrelated/closed issue by @thopa:

"The only last problem that i seem to see as for now is that the last step on both trigseq and trigseq64 gets deleted when the little time dot arrives at that position. Meaning if i enter a step on my ipad on the last step of the sequencers, it gets cleared when the time dot arrives on that last step.Also, i can send signals from voltseq to the mac but it resets the value of each knob on the ipad to 0 once the time dot arrives, at that knob. Random and initialise work fine is just when i input values manually from the ipad knobs that this behaviour happens.Many thanks!"

**Comment by DomiKamu** [comment]
Nice Jason! have git (0.6.0 but fixed voltSeq) now works like a charm, thank you very much!
I'm seeing you're updating to... 0.6.1, btw I'm waiting you've finished, and your announcement on Facebook.
Assuming I can close this issue.
Cheers! Dom.
