### ISSUE TITLE
Osc Communication only working via vcv to ipad osc

### ISSUE THREAD

**Issue by thopa** [j4s0n-c/trowaSoft-VCV#22]
Hi, 
First thanks for your hard work!
I have been trying many different setups with your vcv rack module 0.6 and i have only managed to get osc communication from vcv rack to my ipad, but no signal from my ipad to vcv rack.

Here are some some pictures: 

![d3e091ce-7bfb-43d8-a454-a71eb6c12383](https://user-images.githubusercontent.com/12057639/38117157-d69c9ada-33b3-11e8-89d1-9a0261e82c8a.jpeg)
![414d0d58-709d-406d-9af2-504d97187b3a](https://user-images.githubusercontent.com/12057639/38117158-d6cdf288-33b3-11e8-8285-fa2ff1f3d247.jpeg)
![c8340e2c-6813-42af-8bf7-09c8e9011e05](https://user-images.githubusercontent.com/12057639/38117159-d6f5ecca-33b3-11e8-8316-e00527d3fb53.jpeg)

My mac is running on mac os high sierra, 10.13.3 and touch osc v.1.9.9, both are connected trough a network created om my mac that i join on my ipad. Works fine with other touch osc templates and lemur files which rely on this bidirectional communication.

Its like somehow mac is blocking the port 7001 used by the touchosc ipad app, nut permitting the data from mac to ipad.

Many thanks

**Comment by chichian** [comment]
Hi thopa,

Hmm, did you look at the firewall? I'm not all that familiar with Mac but I think you _may_ need to tell it to allow VCV Rack to receive incoming connections:
https://support.apple.com/en-us/HT201642

> ### Allowing specific applications
> **To allow a specific app to receive incoming connections, add it using Firewall Options:**
> 
> 1. Open System Preferences.
> 2. Click the Security or Security & Privacy icon.
> 3. Select the Firewall tab.
> 4. Click the lock icon in the preference pane, then enter an administrator name and password.
> 5. Click the Firewall Options button
> 6. Click the Add Application (+) button.
> 7. Select the app you want to allow incoming connection privileges for.
> 8. Click Add.
> 9. Click OK.
> 

If it still doesn't work, let us know and we'll try to figure it out. Also, if it does work, then report back and we'll post these instructions under the troubleshooting steps in the Wiki.

Thanks!

**Comment by thopa** [comment]
Many thanks for the quick response, my firewall is turned of but will double check tomorrow when i go back to the studio, ill report back one way or another. Thanks for your support!

**Comment by chichian** [comment]
Oh and another thing. I just noticed that your IPs are on different subnets. I'm not 100% sure that the IPad would be able to send to the Mac (at `192.168.153.x`). Does your Mac have another IP from your Adhoc network you created (one that is also like `169.254.x.x`)? If so, use _that_ IP on the IPad as the Host address.

**Comment by thopa** [comment]
Well spotted! Ill give it a go in the morning, will check if when creating the ad hoc (which seems to be the most direct connection between computer and ipad) the mac ip is different from the one showing up on the osc app. Weird signal can go one way but not the other. Will report back. Many thanks!

**Comment by thopa** [comment]
Hi! Good news that fixed it. When creating the ad hoc mac and ipad where on different subnets. Changing the ip address on the ipad to the ip  shown on the mac network preferences solved it.

**Comment by thopa** [comment]
The only last problem that i seem to see as for now is that the last step on both trigseq and trigseq64 gets deleted when the little time dot arrives at that position. Meaning if i enter a step on my ipad on the last step of the sequencers, it gets cleared when the time dot arrives on that last step. 

Also, i can send signals from voltseq to the mac but it resets the value of each knob on the ipad to 0 once the time dot arrives, at that knob. Random and initialise work fine is just when i input values manually from the ipad knobs that this behaviour happens.

Many thanks!

**Comment by j4s0n-c** [comment]
Glad you got the communication part going. Thanks for the feedback. Since these are different issues and there is already an open issue about bad TouchOSC interaction, I will close this one and paste your last comment in that issue till it is resolved.

**Comment by thopa** [comment]
Thanks!

**Comment by thopa** [comment]
Hi!
Sorry for the late reply...kids to take care off!
I have found the bug, once i set the settings like this om my ipad the reset problems are gone.
Hope this helps troubleshooting
![98ed7114-aff6-41e2-9b9b-027618d21723](https://user-images.githubusercontent.com/12057639/38382553-8b3d2558-390a-11e8-9b8a-cbeacfe4072b.jpeg)
