### ISSUE TITLE
TouchOSC strange behavior on Mac

### ISSUE THREAD

**Issue by j4s0n-c** [j4s0n-c/trowaSoft-VCV#23]
Copied from another unrelated/closed issue by @thopa:

"The only last problem that i seem to see as for now is that the last step on both trigseq and trigseq64 gets deleted when the little time dot arrives at that position. Meaning if i enter a step on my ipad on the last step of the sequencers, it gets cleared when the time dot arrives on that last step.Also, i can send signals from voltseq to the mac but it resets the value of each knob on the ipad to 0 once the time dot arrives, at that knob. Random and initialise work fine is just when i input values manually from the ipad knobs that this behaviour happens.Many thanks!"

**Comment by j4s0n-c** [comment]
@thopa : I cannot reproduce this issue on Windows, Mac, or Linux. I went through the TouchOSC layout with the editor on mac, fixed a copy paste issue on the mode labels for voltSeq, then synced that layout with my iPad. I have no issue with the last step on trigSeq or trigSeq64. I will upload the fixed layout, but there was no issue that would cause these symptoms. Please make sure you are using the latest version of TouchOSC on your iPad and the latest version of the TouchOSC Editor on your Mac. Newer versions have changes/ new features and the editor and app have to be updated together for it to work properly. Latest editor (version 1.4.0.1) here: https://hexler.net/software/touchosc#downloads. iPad version should be 1.9.9 -- Update on iPad through app store, of course.

**Comment by j4s0n-c** [comment]
@thopa I'm removing the [BUG] tag for now. Please let me know if updating app and editor solves the issue for you.

**Comment by thopa** [comment]
I will and report assap. Thanks
