### ISSUE TITLE
Change sequencers of Trigseq and VoltSeq from midi Fighter Twister

### ISSUE THREAD

**Issue by thopa** [j4s0n-c/trowaSoft-VCV#25]
Hi!
Testing the pd patches alongside the midi fighter twister, excellent work!
How can i change sequencers from the midi fighter like on the  touch osc template?
Is this implemented?
Thanks

**Comment by thopa** [comment]
Sorry, just read the description about the implementation at the moment.
Cheers

**Comment by j4s0n-c** [comment]
Do you mean changing the current edit channel/pattern? For that, I'd use another page on the midi fighter as a "config" page, and send the proper OSC messages. Or, maybe pick 2 side buttons and make them inc/dec the values. I'll look into adding this to the pd patch when I can. You are, of course, welcome to rip it open and dive in as well.

**Comment by thopa** [comment]
Yes exactly! Sorry im a completely noob with pd.
What messages do the midi fighter need to send to change channels? Guess i could look into the touch osc template but as i say dont know how to implement it on pd
Can help you out with the lemur templates though :)
Many thanks for the great support!

**Comment by j4s0n-c** [comment]
The detailed OSC implementation is here...
https://github.com/j4s0n-c/trowaSoft-VCV/wiki/Open-Sound-Control-(OSC)-Interface
I'm actually digging in to the pd patch right now to see what I can do with that.

**Comment by thopa** [comment]
thanks a lot for looking into it.
would be great to have the second page on the twister choose the editing channel via tsseq/edit/ch and third page choose pattern via /tsseq/edit/pat . As i said i don’t know much about pd but being a osc to midi converter it would mean assign a cc in the twister and convert that to a osc message inside pd. Wish i could be of more help!

**Comment by j4s0n-c** [comment]
@thopa Please try this new pd patch and MF template file. The top and bottom buttons on the left/right side of MFTwister will scroll thru and wrap around patterns 1-64 / channels 1-16 on both modules simultaneously. I also exploded and cleaned up the pd patch so you and others can hopefully learn a thing or 12 about pd and OSC.
https://github.com/j4s0n-c/trowaSoft-VCV/releases/download/v0.6.1/trigSeq_voltSeq_MIDI_Fighter_Twister_V2.pd
https://github.com/j4s0n-c/trowaSoft-VCV/releases/download/v0.6.1/trigSeq_voltSeq_MIDI_Fighter_Twister_V2.mfs

**Comment by thopa** [comment]
Wow! amazing! Thanks a lot much appreciated, and sorry for the noobness on pd!!!!
I have this lemur template for the mfs with led feedback and many other features, maybe its time to dig Puredata!!!
![7550_img_2427_1](https://user-images.githubusercontent.com/12057639/38412382-8b40d714-3989-11e8-9d4e-f49e26edc58d.jpg)
