### ISSUE TITLE
oscCV signal issues

### ISSUE THREAD

**Issue by Macciza** [j4s0n-c/trowaSoft-VCV#26]
Hi 
Great to see that there is at least some OSC presence in VCV, thanks ...

A few comments on first use....

1. The visual feedback could be improved. It seems most modules use Green for a positive signal and Red for a negative one but oscCV seems to only use Red?? 

2. The 'oscilloscope' display seems to have the signal inverted?? Positive values go down in graph and Negative go up??

Apart from that all has run well for me so far ....

Cheers
Macciza

**Comment by j4s0n-c** [comment]
Thanks for the feedback. All of our modules use the channel color for LED feedback on the jacks. So ch 1 should be red, 2 orange, and so on. Same color for +/- voltage and  0v = LED off. The mini scopes are inverted and we will be flipping them and adjusting the timing for a "prettier" display in the next update.
