### ISSUE TITLE
Feature Request (cvOSCcv) - Multiple instances using the same IO port

### ISSUE THREAD

**Issue by Outboarder** [j4s0n-c/trowaSoft-VCV#27]
Hi Jason.
I'm using this fabulous module (cvOSCcv) and so far enjoying it.
The only thing that I wish it had is support for using the same IO port in other instances ,this will helps to extend the number of IO's on the same port.
Is it coming on next version ?

Thank you for all the goods you share.

**Comment by j4s0n-c** [comment]
It isn't as easy as it seems  like it should be to do this in the modules directly. The workaround is to use Purr-Data to route the OSC however you like,
[https://github.com/agraef/purr-data/releases](https://github.com/agraef/purr-data/releases)
Here is an example patch to get you started... 
[http://www.geekasaurusrex.net/file.axd?file=2018%2f4%2fosc_router_example.pd](http://www.geekasaurusrex.net/file.axd?file=2018%2f4%2fosc_router_example.pd)

**Comment by Outboarder** [comment]
I'm familiar with PD ,also I tested osc in VVVV it works but for some reason it constantly put random 0 between messages. I will check PD and report back.

You Rock

**Comment by Outboarder** [comment]
The example PD patch helped me a lot and worked as it's expected.
I use it to connect several cvOSCsv instances via same IP and different ports to Blender.  
Here is my twick: 
https://imgur.com/9DLl717
https://drive.google.com/open?id=11hvQYoLFc5IC0MH7g7D6H_ILrqJNv7jA 
Thanks again.

**Comment by Outboarder** [comment]
Thank you very much for the latest update, no need for PD anymore.

**Comment by j4s0n-c** [comment]
@Outboarder You're very welcome!
