### ISSUE TITLE
Modules crash under Rack 0.6.1

### ISSUE THREAD

**Issue by caecos** [j4s0n-c/trowaSoft-VCV#28]
Cannot load modules using Rack 0.6.1

**Comment by caecos** [comment]
I'm on Windows 10 Pro (Asus Laptop Rog Republic)

**Comment by j4s0n-c** [comment]
Thanks for the feedback. We have it working and it should be up soon. We also use ROG laptops. Good choice.

**Comment by j4s0n-c** [comment]
0.6.1 Update is up and working for us. Enjoy.

**Comment by caecos** [comment]
Many thanks, I will compile the source as soon as the compilation for the latest Rack has finished...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by caecos** [comment]
Up and running…thx…

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : j4s0n-c <notifications@github.com>
Envoyé : Monday, June 11, 2018 4:11:11 AM
À : j4s0n-c/trowaSoft-VCV
Cc : caecos; Author
Objet : Re: [j4s0n-c/trowaSoft-VCV] Modules crash under Rack 0.6.1 (#28)


Thanks for the feedback. We have it working and it should be up soon. We also use ROG laptops. Good choice.
