### ISSUE TITLE
trigseq initialize does not function

### ISSUE THREAD

**Issue by joopvdl** [j4s0n-c/trowaSoft-VCV#3]

**Comment by chichian** [comment]
Oops. I thought that was deprecated. We can add it back next release if it's still valid.

**Comment by joopvdl** [comment]
I think it's very useful to reset the entire seq, yes. These are my favorites by far, and to reset all the sequences individually is quite a bit of work :)

**Comment by chichian** [comment]
This should be fixed in the latest release (v0.5.5.1). Thanks for reporting.
