### ISSUE TITLE
Attempting to Connect a Launchpad Pro to trigseq-64

### ISSUE THREAD

**Issue by ichthyoidoc** [j4s0n-c/trowaSoft-VCV#30]
Hi, I'm attempting to connect my Launchpad Pro to trigseq-64. Currently, I've gotten the communication to work from the default launchpad .pd file with the Launchpad Pro's Live port. However, the buttons are all wrongly mapped, and so the wrong buttons light up while playing. Is there any thing I can do on my side to make this work?

**Comment by j4s0n-c** [comment]
Cool. You would need to edit the pd patch to use the proper midi note range using the document here...
https://global.novationmusic.com/sites/default/files/novation/downloads/10598/launchpad-pro-programmers-reference-guide_0.pdf
Check out the programmer layout section, page 17.

**Comment by j4s0n-c** [comment]
...In the trigSeq64_Launchpad.pd patch right click on the dark blue areas of the [MIDI I/O Patch] and the [OSC Config] &  click "Open" That is where the actual patches handling MIDI to and from the Launchpad are "hidden".

**Comment by ichthyoidoc** [comment]
thanks for the quick reply!

I actually have very little programming experience. Looking at the PD file, it seems a little bit more complex. Is there any guide to changing the various pad numbers and things?

**Comment by j4s0n-c** [comment]
Grab this one instead. http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_Launchpad_7-2018.pd
I exploded all the subpatches so you can see whats going on without having to dig. You might just need to change a few expressions. Lemme see how far I can get you without having one here to test ;)

**Comment by ichthyoidoc** [comment]
great. let me take a look and see if i can understand. is there a better channel to communicate? or is this the best?

**Comment by ichthyoidoc** [comment]
so one problem i've found is that, vs. the launchpad mini's, it looks like the Launchpad pro actually goes bottom up instead of top down for midi notes. (really strange). Also, since there are 4 sides, the normal expressions excluding the side and top bar have to be added to in order to exclude the left bar and bottom bar of the launchpad pro (all of them sharing midi cc between 1-98).

I think that means that more than just a few expressions have to be changed. I think moreso that expressions have to be added to exclude the new bars, and maybe also needs some kind of reverse to go top down for the Launchpad Pro.

i feel like i just opened a massive can of worms, lol.

**Comment by j4s0n-c** [comment]
I don't mind using github to discuss. Then others can learn from our work as well.

Sounds about right. Except on the LP pro the grid buttons send notes and all other buttons send CCs. so it's actually easier to sort them out. Everything on the right side of the pd patch would be for sorting the CCs and sending the proper OSC to trigSeq. Just add the proper CCs to the route block and wire them to individual "/tsseq/edit/ch x" OSC messages. All the sidebtn sorting crap on the notes side can go away but you still need the part that clears and sets the LEDs for which channel is being edited. The [uzi] and stuff... The expression near the bottom left of the patch should be the only thing that needs to be changed to reverse the row order of the grid and add the offset for starting at 11 and only skip 2 notes per row instead of 8, etc...

**Comment by j4s0n-c** [comment]
Actually... looking at page 17 again I realize they already laid the whole controller out in ROW/COLUMN. HA!

**Comment by ichthyoidoc** [comment]
Yes, and that's what threw me off a bit. would the expressions have to be done row by row? and then do separate ones for each left/right/top/bottom bar?

**Comment by j4s0n-c** [comment]
Try this:
http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_LP_Pro_7-2018.pd
The colors are probably the only thing left to fix...

**Comment by ichthyoidoc** [comment]
I think it's almost there. the 'shift' button (81) is still included in the top row, which shifts everything over and up one and excludes the last pad (18) at the bottom right. also, when I press the pads to try to place something in the sequencer, nothing happens. the error I get in PD is this: 
<img width="1440" alt="screen shot 2018-07-23 at 10 27 22 am" src="https://user-images.githubusercontent.com/36090654/43092946-956718f0-8e63-11e8-97f2-58b15a39c24d.png">
Thanks so much for your help!

**Comment by ichthyoidoc** [comment]
huh. I just noticed. with this particular file, no matter the edit i make, nothing happens? Maybe I'm doing something wrong. Is there a compile function I need to do before the changes I make affect the actual file?

UPDATE: scratch that. lol, made multiple copies and was deleting the wrong stuff.

**Comment by ichthyoidoc** [comment]
scratch that. lol, made multiple copies and was deleting the wrong stuff.

**Comment by ichthyoidoc** [comment]
Ok, after messing with it a bit, i'm able to input the pads again. I actually don't know why, but i'm no longer getting the udpsend error from before. 

However, the pads are still mis-placed. If I press a pad on the LP-Pro, it'll toggle the pad before it. Here's a picture:
![img_0156](https://user-images.githubusercontent.com/36090654/43098058-d2dae8c4-8e72-11e8-8bac-6ba928e62487.JPG)
Hope that makes sense. The channel buttons are similar. The top RHS button and the second below it both go to channel 1. The rest go in order after that (button 3 goes to channel 2, etc.) all the way to USER + the bottom RHS button, which goes to channel 15. So basically, channel 16 is inaccessible from the LP Pro.

The 2nd and 3rd rows didn't work at all for some reason.

After restarting the entire thing, the buttons are unresponsive again and I get the upsend error.

Again, thanks for your help. I'm sure this is some kind of headache.

**Comment by j4s0n-c** [comment]
Yeah, if you had multiple copies of the patch open they were trying to access the same OSC ports and blocking each other. I made a virtual LP Pro in TouchOSC so I could figure this out... try this patch:
http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_LP_Pro_7-2018.pd

**Comment by ichthyoidoc** [comment]
YES, this works! so far, haha. However, there's still the light button that's one grid off. Here's a picture:
![img_0157](https://user-images.githubusercontent.com/36090654/43101222-ad378514-8e7c-11e8-9571-6eec05d59ecb.JPG)

Everything else so far (when the patch is inputting correctly) is working.

**Comment by j4s0n-c** [comment]
Ok, right side buttons should work and light up when ch is changed from module or LP. The step grid was working fine on this end. Does the top left circle light up instead of step 1 when toggled via the module? Or when changing channel?
http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_LP_Pro_Draft.pd

**Comment by ichthyoidoc** [comment]
the top left circle (blue shift) lights up as if it's the same as the first top left pad. the bottom right pad doesn't light up at all. So i think everything is just shifted over one.

i should clarify: the blue light is the "follow" light that goes through the different steps. It isn't the actual pad toggle light (which is yellow). The toggle lights are perfectly fine.

Hope that clears it up?

P.S. The new one's channel buttons work perfectly. thanks!

**Comment by j4s0n-c** [comment]
Ok, try this: http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_LP_Pro_Draft.pd
We called them PLAYHEAD and ACTIVE STEPS in the patch comments, you can change the colors (currently 60 and 15) to whatever you want from page 6.

**Comment by ichthyoidoc** [comment]
so the playhead problem is fixed, but perhaps not the active steps. The playhead now moves the active steps ahead one column whenever they are active. I don't know how else to describe it. Here's a video (from my dropbox, hope it works.):

https://www.dropbox.com/s/tyjzksn96efatxu/IMG_0159.MOV?dl=0

The launchpad is rotated in the clip. The playhead doesn't actually go up/down. My phone just didn't rotate right.

Just to clarify, the steps in the trigSeq64 don't actually move like the active steps seem to on the LP Pro. It's just purely on the LP pro that this happens. All other buttons currently work fine.

**Comment by j4s0n-c** [comment]
Ok this one should fix that and the Play button should now light up when playing.
http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_LP_Pro_Draft.pd

**Comment by ichthyoidoc** [comment]
awesome! it's completely functional now. However, there is a "follow light" that follows the playhead. Don't know if this was intentional? When it finishes the grid, on the LP Pro, it leaves a last red playhead marker at the bottom.

![img_0160](https://user-images.githubusercontent.com/36090654/43153047-0c141edc-8f25-11e8-8b58-fd056b321935.JPG)

If the length of the sequence is shortened in the module, it'll also leave a red playhead at the last pad of the length's end. Switching to another channel and back again gets rid of the red marker.

I think that's about it though. It's 100% functional, and the mark left at the end doesn't make any noises or toggles.

Thanks so much! You've been so helpful! I'm planning on using this in my next patch. Would it be ok to give you a shoutout when I upload it to patch storage and Youtube?

**Comment by ichthyoidoc** [comment]
i did get this error. Not sure what it is?

<img width="1440" alt="screen shot 2018-07-24 at 11 15 44 am" src="https://user-images.githubusercontent.com/36090654/43157954-4714aa48-8f33-11e8-8333-04e1eb2a87a0.png">

It doesn't have any affect on functionality though.

**Comment by ichthyoidoc** [comment]
found another slight bug, but again doesn't have an effect on functionality. Like the bug in the comment before previous, this one just leaves a light. Here's a picture:

![img_0162](https://user-images.githubusercontent.com/36090654/43218408-2914e1b8-8ff9-11e8-8ede-04ea9d2866db.JPG)

Hope that makes sense. This only happens to the bottom right pad. So when the that bottom right pad is toggled, when the playhead moves over it, it pushes the light back one step. It doesn't actually do anything in the module though. If I toggle both the bottom right pad and the second to last one to the left of it, this bug doesn't happen (although the previous red marker bug does still happen).

Thanks again for all your hard work! It's been SO much better/easier programming the module with the LP-Pro working.

**Comment by j4s0n-c** [comment]
Oops! had more plans than I thought yesterday... try this. Should have fixed the trailing LED and color per channel feedback on the grid. Sometimes still get a stuck LED when switching channels.
http://www.geekasaurusrex.net/file.axd?file=2018%2f7%2ftrigSeq64_LP_Pro_Draft.pd

**Comment by ichthyoidoc** [comment]
hey! sorry for the late response, haha, my weekend was crazy.

yes! it looks fixed now. the LED does get stuck when switching channels sometimes and changing modes, but very little. the colors work perfectly and there's no longer a trailing LED on the playhead.

Thanks! Let me know if there's anything else you need from me to test the Launchpad Pro. It all looks good from here though!

**Comment by ichthyoidoc** [comment]
Also: I've been using both the Live port and the User Program mode of the LP-Pro. It looks like your mapping works for both! So if anyone asks, they can use both modes :-)
