### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by alaction** [j4s0n-c/trowaSoft-VCV#31]
Hello, I've had an issue with the Trowasoft module :
 It doesn't seems to update correctly, or to load correctly.
I am on VCV 0.6.0., and don't find the log anywhere.
 By the way, great modules !

![loadingissue](https://user-images.githubusercontent.com/42639201/44517928-3f927400-a6c9-11e8-868a-b120a007dfd9.PNG)

**Comment by j4s0n-c** [comment]
Current version of Rack is 0.6.2b https://vcvrack.com/. The latest version of our plugins are built against the latest version of Rack. You can use an old release from here https://github.com/j4s0n-c/trowaSoft-VCV/releases if you must, but I would not recommend it.
