### ISSUE TITLE
cvOSCcv unnecessarily sends bundle messages

### ISSUE THREAD

**Issue by korfuri** [j4s0n-c/trowaSoft-VCV#35]
It appears that cvOSCcv always sends its messages as bundles, regardless of whether it's sending one or more values. This is fine by OSC standards AFAICT but I'm working with a system that does not support bundles (https://github.com/samaaron/sonic-pi/issues/2085) and that's making it impossible for me to send OSC data from VCV to it. Would it be possible to un-bundle messages when a single value is sent? I realize that this effectively means that I will only be able to use a single channel at a time, but it would be better than nothing.

**Comment by chichian** [comment]
Hi korfuri,

Sorry to get back late, but did you still need this? I am working currently on some revisions to cvOSCcv. From following the Sonic Pi thread, it looks like it can support bundles now?

**Comment by korfuri** [comment]
I don't think Sonic Pi has landed support for bundles yet. On my side I'm using a workaround (I patched the ruby implementation of OSC in Sonic Pi and I use a hack to force Sonic Pi to use that code instead of the native version), so it's not a urgent need for me. I think it's just a nice-to-have for cvOSCcv to not bundle what doesn't need bundling, but I don't think it's important or urgent. (I may be wrong: maybe other implementations of OSC decoding in the real world also don't understand bundles, I don't know).

So I don't really need it, and in general, the fix should be on the Sonic Pi side, but if you happen to change cvOSCcv and you see an opportunity to remove bundling when it's not required, I think it's still a plus for everyone.
