### ISSUE TITLE
Proposal to conversion against Rack v1 !

### ISSUE THREAD

**Issue by DomiKamu** [j4s0n-c/trowaSoft-VCV#36]
Hi Jason, it's not an issue, but a proposal from me to take a look about Rack v1 port of your plugin.

Advise me if you're okay (I don't know if you're working on it, or not).

Regards,
Dominique Camus (Ohmer Modules & OhmerPrems)

**Comment by j4s0n-c** [comment]
Hey,
I know we've been very quiet for a while. We are working on getting our modules v1 compatible.

**Comment by DomiKamu** [comment]
Hi again, it's an excellent news, so I (we) wait for your conversion to v1. I close this "issue" ;)

**Comment by j4s0n-c** [comment]
trowaSoft Modules for VCV Rack v.1.x conversion complete!
multiScope now works on MacOS and we added a resizable (down to 1hp) blank panel.
submitted to VCV Library, Win & Mac builds are available @ github releases.
