### ISSUE TITLE
v1 

### ISSUE THREAD

**Issue by Coirt** [j4s0n-c/trowaSoft-VCV#37]
Any plans to migrate to v1?

**Comment by j4s0n-c** [comment]
See Issue #36

**Comment by Coirt** [comment]
Ah, didn't see will close!

**Comment by j4s0n-c** [comment]
I reopened it in case anyone else has the same question before we are able
to release. Thank you for you interest and patience.

**Comment by j4s0n-c** [comment]
trowaSoft Modules for VCV Rack v.1.x conversion complete!
multiScope now works on MacOS and we added a resizable (down to 1hp) blank panel.
submitted to VCV Library, Win & Mac builds are available @ github releases.
