### ISSUE TITLE
v1 port shadow size, border:port ratio

### ISSUE THREAD

**Issue by Coirt** [j4s0n-c/trowaSoft-VCV#38]
Hi Jason, would you consider decreasing the shadow size on ports? it just looks wrong:

![rackShadow](https://user-images.githubusercontent.com/12150421/62205802-289fdb80-b388-11e9-8485-b819a790c180.PNG)

You could do this a couple of ways the hard way would be decreasing the border size in the port.svg
![shadow boxsize](https://user-images.githubusercontent.com/12150421/62205844-453c1380-b388-11e9-9a72-1def80fb0a54.PNG)

`shadow->opacity = 0.f;` create a custom size for the border/port ratio. Just the override might be sufficient.
see: https://github.com/VCVRack/Rack/blob/v1/include/app/CircularShadow.hpp#L15

The issue is the border size of the port but because you would have to edit all port positions after resizing the border it would be easier to create a custom shadow for the port border size. 

https://github.com/VCVRack/Rack/blob/v1/src/app/CircularShadow.cpp#L14

**Comment by chichian** [comment]
Thanks Coirt. That was ugly! I didn't really notice during the conversion to v1 API since I have a small screen and only really focused on getting the modules to "work". 

I implemented your suggestion of turning the opacity off for the circular shadows.
