### ISSUE TITLE
Touch OSC can't edit sequence

### ISSUE THREAD

**Issue by Dzuco** [j4s0n-c/trowaSoft-VCV#39]
Hi I have an issue with the new version (v 1.0.1), The plugins are talking to TouchOSC and vice versa. but I can't set a sequence with the grid, faders and buttons are working properly though. 

I saved an older version of vcv wich has an older version of trowaSoft plugins, this version works with no issues.

I've noticed this issue creating an interface for a project on lemur, sniffing data with osculator, also I found your OSC implementation info very useful.

thank you for creating such great tools.

**Comment by j4s0n-c** [comment]
Just found this last night myself. Conversion to v1 was not as smooth as we hoped. We will have a fix up on github later this evening. Probably wont push to the Plugin Library until we have a few more things added/fixed though.

**Comment by j4s0n-c** [comment]
@Dzuco The fix is up. Are you able to compile? If not, I can upload a build for it. What OS are you using?

**Comment by Dzuco** [comment]
@j4s0n-c Unfortunately I don't know how to. I am using macOS mojave.

**Comment by j4s0n-c** [comment]
@Dzuco Please extract the **plugin.dylib** in this zip over the one in **~/Documents/Rack/plugins-v1/trowaSoft** and let me know how it goes.

[trowaSoft-1.0.1-mac.zip](https://github.com/j4s0n-c/trowaSoft-VCV/files/3479972/trowaSoft-1.0.1-mac.zip)

**Comment by Dzuco** [comment]
Thank for answering so quickly, I've been busy lately so, sorry for that. But I tried the file you sent, and the issue has been solved.

**Comment by marcusbrutulus** [comment]
I have the same issue. All buttons work except for the grid sequence itself - so can't edit the sequence. Has this been fixed? If so, where do I d/l the latest?

**Comment by marcusbrutulus** [comment]
Disregard the previous. I copied over the dylib file and all works well. Thanks!

**Comment by mocca14** [comment]
on v 1.0.2  still cant edit sequence

**Comment by j4s0n-c** [comment]
> on v 1.0.2 still cant edit sequence

Please update to the latest version of rack.

**Comment by j4s0n-c** [comment]
Tested with v. 1.0.2 and original touchOSC layout , and everything seems to work fine. Closing Issue.
