### ISSUE TITLE
trowasoft

### ISSUE THREAD

**Issue by ghost** [j4s0n-c/trowaSoft-VCV#4]
Hi! 

I just merged your pull request in the plugin manager... tried it afterwards and saw that your modules still show the red dot (for a new update) after downloading... so i checked your makefile here on github.. if this is the same one you used for the latest build pls take a look at the makefile from the tutorial:
https://github.com/VCVRack/Tutorial/blob/master/Makefile

e.g. missing "VERSION= ......" in your makefile

Greetings,
Michael

**Comment by ghost** [comment]
btw I really like your modules!!

**Comment by j4s0n-c** [comment]
Thanks for the heads up & the compliment. Issues should be corrected now.
Checks pending for updated manifest.

**Comment by ghost** [comment]
yea it was still a pending check but i merged it anyway because the json file looked good... tried it on my windows system .. now it works properly without showing the red dot
