### ISSUE TITLE
cvOSCcv Presets Not Saved

### ISSUE THREAD

**Issue by midiguru** [j4s0n-c/trowaSoft-VCV#42]
I think this is a major problem. I want to use cvOSCcv to receive incoming messages from touchOSC on my iPad. So I created a nice set of control names in the right column, opened the Advanced panel, and gave each of them the I/O values I wanted. So far, so good.

I then used the VCV Duplicate command to make a new module, with the idea of making its namespace trowacv2. But it didn't work. For some reason, it duplicated the quasi-random dumb control names I had inserted yesterday, not the ones I had just now carefully created. The Advanced settings, however, _were_ properly duplicated.

Worse was yet to come. I saved the Preset using the context menu, created a new cvOSCcv module, and loaded the saved Preset. But what was saved was yesterday's garbage control names, not the nice ones I had just created.

I then saved my VCV patch, opened a different patch, and went back to the Trowasoft test patch. At this point, again, I get the garbage channel names from yesterday. The new text values I entered this morning will apparently have to be entered each and every time I want to use cvOSCcv.

At the moment, I'd call this a deal-breaker. I sure hope you can fix it! I've encountered a similar preset-saving problem with a module from some other developer, at the moment I don't remember who. There are always these little issues -- I'm not freaking out, I'm just hoping you'll have time to update the module. Thanks!

**Comment by chichian** [comment]
Hi midiguru,

It doesn't save the channel names unless you hide the config again (on hiding, it will save the names, but it doesn't save them while the config is open). Could this have been the issue maybe? I can't seem to replicate this issue otherwise.

I do see that if you don't perform a successful connect first, the namespace isn't being saved. I will fix that though.

**Comment by j4s0n-c** [comment]
Hey @midiguru,
Hope all is well. I'm just going through trying to close all old open issues. Would you say this one is resolved?
