### ISSUE TITLE
Unable to Use Multiple Instances of cvOSCcv

### ISSUE THREAD

**Issue by midiguru** [j4s0n-c/trowaSoft-VCV#43]
Note: I solve my earlier problem (more or less) by deleting the plug-in folder and re-downloading it. That got rid of my garbage channel names. Okay, I'll just use the default channel names -- no problem.

But here's the new problem. Eight channels of control are not enough! So I create a second cvOSCcv, give it the namespace trowacv2, and use touchOSC Editor to assign a second bank of control widgets to trowacv2. But cvOSCcv will not let me make an OSC connection with the second module. So it appears I'm limited to only eight OSC connections, total, in spite of the fact that touchOSC can have 20 or 50 widgets in a template.

Also, the error message says, "Error connecting to 127.0.0.1" -- but that's not the IP address used by either of the modules. They're both set to 192.168.1.67, and that works fine for the first module, but not for the second. So the error message is wonky, but that's not the main problem. The main problem is, I will need to run at least four cvOSCcv modules at once, each with its own namespace identifier.

How can I do that? Is this a user error, or will it require an updated version?

**Comment by midiguru** [comment]
To further clarify, I can connect the second module to 192.168.1.67 if I use I/O ports 7002 and 7003. However, as far as I'm able to determine, touchOSC does not allow the port number to be set. That setting is not visible in either the Editor program or the touchOSC Options in the iPad. (Not that we would expect it to be visible on the iPad, as it would be global if it were, not settable per widget.)

Is there a way to get one touchOSC to transmit on two ports at once? That would apparently solve the problem.

**Comment by chichian** [comment]
Hi midiguru,

Yes, in the current version, it doesn't allow more than module to use the same ports. The release we are working now will remove this restriction on cvOSCcv. So yes it is in the pipeline :) as well as expanders (use one module but add more inputs/outputs).

**Comment by midiguru** [comment]
I'll be looking forward to seeing the update. In the meantime I'm using Holonic Source. I would prefer cvOSCcv because of its dual CV and trigger outputs per channel, but at the moment I have 64 channels of incoming OSC signals to play with, so I can send triggers separately.
