### ISSUE TITLE
Can't synchronize two CVC trigSeq

### ISSUE THREAD

**Issue by MockbaTheBorg** [j4s0n-c/trowaSoft-VCV#45]
Hi Jason,

I am trying the following scenario:
On computer A (master) I have set up the sequencer to send broadcast on port 7000
![Machine_A_master](https://user-images.githubusercontent.com/16762507/66539412-c684f480-eaf5-11e9-8926-8c9f19f80757.png)

On computer B (slave) I have set up the sequencer to receive on port 7000
![Machine_B_slave](https://user-images.githubusercontent.com/16762507/66539469-fcc27400-eaf5-11e9-8d21-dcabcd1d1af1.png)

If I change the sequencer knobs on computer A, except the tempo one, they change accordingly on computer B, however when I press RUN on computer A, the sequencer stops on computer B, and vice-versa. The tempo knob doesn't seem to have any effect on the slave.
So I can not manage to have both sequencers running in sync (on synchronized tempo and reset).
The CPY button for the channel seems to turn on-off in sync among the two computers, but the one for the pattern is inverted, turns off at the slave when I turn on at the master and vice-versa, just like the RUN button.

So, either I completely misunderstood how this is supposed to work, and am expecting it to be something completely different from what it really is, or things are not working correctly.
I have tried sending to broadcast, sending directly to the slave IP, using external clock, internal (trigSeq) clock, you name it ... all possible combinations ... to no avail.
Any guidance here would be greatly appreciated.
My target is: have two computers running VCV and synchronize the tempo of the slave to the master.

Thanks!

**Comment by j4s0n-c** [comment]
The intended usage of OSC for the sequencers is for remote control, pattern entry, and visual feedback to/from a TouchOSC layout or any grid/knob based MIDI control surface connected to a purr-data patch that has two-way OSC communication with the module. Looks like you found an easter egg where the visual feedback messages coming out of module A are actually controlling module B. This could be developed into an actual remote sync feature but this is just a feedback loop ;) 
**HOWEVER!**... try this:

**### Master Patch**
The first trigSeq is the master reset and clock pulse generator. Ch 1 is pattern reset signal once every 64 steps.
![VCV Rack OSC Sequencer Sync Master A](https://user-images.githubusercontent.com/4063528/66554083-2634cd00-eb01-11e9-9d0d-087d26370238.png)
Ch 2 is the Master clock pulse at 64/cycle. you could use other channels to have other clock divisions...
![VCV Rack OSC Sequencer Sync Master B](https://user-images.githubusercontent.com/4063528/66554713-5630a000-eb02-11e9-8aec-c8de7acb0cdc.png)
**Modules:**
Row 1: RJModules Button (Master Reset Button), trowaSoft trigSeq64 (Master clock/reset pulse generator), trowaSoft cvOSCcv (send clock, reset, and pattern number over OSC), Bacon Music Sample Delay (to line up the local sequencers with the remote ones), trowaSoft trigSeq64 (master drum sequencer)
Row 2: trowaSoft voltSeq (pattern selector, clocked by the pattern reset signal once every 64 steps. chooses which pattern is playing on the local and remote sequencers, could use multiple channels for different ones on each), Erica PicoDrums, VCV Audio-8

**SLAVE PATCH**
![VCV Rack OSC Sequencer Sync Slave A](https://user-images.githubusercontent.com/4063528/66556181-9d1f9500-eb04-11e9-8cc8-2d1fd9582c6d.png)
**Modules**: trowaSoft cvOSCcv (get RESET, PATTERN, and CLOCK from master), trowaSoft trigSeq64 (drum sequencer), Erica PicoDrums, VCV Audio-8

You should now be able to playback up to 16 different patterns in order on multiple sequencers across multiple machines. IP and OUT port on slave don't matter. If a packet is lost on the network things will get out of sync but will line back up on step 1 of the next pattern. Or, press the big button on the master to reset manually. It worked pretty well for me (even over wifi) during this write-up. Let me know how you get along.

**Comment by MockbaTheBorg** [comment]
Awesome!

Yeah, I had tried something similar with good results after I wrote the
issue, just thought it was too cumbersome.

But ok, so I misunderstood how it should work indeed, you can go ahead and
close the issue.

Thanks a lot for your help.

Cheers,
Marcelo

**Comment by MockbaTheBorg** [comment]
Tested here with a slightly simplified setup over ethernet ... works perfectly. Thanks!!!
