### ISSUE TITLE
Minor tweak to build on Linux

### ISSUE THREAD

**Issue by Chaircrusher** [j4s0n-c/trowaSoft-VCV#5]
On Centos7 the compilers are older than the standard, and this one minor tweak is the difference between the build succeeding and failing -- the version of std::regex_replace won't take a string constant as the last argument.  This should work with every C++ compiler.  I've tested it with CLang as well...

diff --git a/src/TSTextField.cpp b/src/TSTextField.cpp
index 88390f6..53c1110 100644
--- a/src/TSTextField.cpp
+++ b/src/TSTextField.cpp
@@ -37,7 +37,7 @@ std::string TSTextField::cleanseString(std::string newText)
 	{
 		// Remove invalid chars
 		std::stringstream cleansedStr;
-		std::regex_replace(std::ostream_iterator<char>(cleansedStr), newText.begin(), newText.end(), regexInvalidChar, "");
+		std::regex_replace(std::ostream_iterator<char>(cleansedStr), newText.begin(), newText.end(), regexInvalidChar, std::string(""));
 		return cleansedStr.str().substr(0, maxLength);
 	}
 } // end cleanseString()

**Comment by chichian** [comment]
Thank you for reporting and fixing :). Will update it in next release. Sorry for the late response. It's been busy IRL.

**Comment by chichian** [comment]
Hi Chaircrusher, 

Thank you again. Your changes have been incorporated in the [0.5.5.2 release](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v0.5.5.2).
