### ISSUE TITLE
Receive OSC vectors in cvOSCcv

### ISSUE THREAD

**Issue by nesdnuma** [j4s0n-c/trowaSoft-VCV#52]
Hello,

Most OSC gesture interface programs have an XY pad widget sending vectors of 2 data containing the x and y position for each finger touching the surface.

It would be nice if cvOSCcv could handle those messages, for instance by splitting the x and the y on two different CV outputs. This would mean adding a second column of CV outputs to the module. An alternative would be to upgrade the "Advanced" decoding panel and allow some tool to select either data [0] or data [1] within the message.

**Comment by j4s0n-c** [comment]
@nesdnuma  cvOSCcv channels are polyphonic.

For a multixy pad in touchOSC (assuming first multixy on page one):
- [ ] set channel 1 in cvOSCcv to receive "/1/multixy1/1" for the first finger, channel 2 to receive "/1/multixy1/2" for the second finger and so on...
- [ ] make sure the "ADV" page is set to convert the values correctly.
- [ ] Connect the "VAL" output of each channel to a VCV Split module to access the individual values.
- [ ] Enjoy.

It also works for lemur Breakpoint, and  other multi-whatever objects, up to 16 points/channels each. For more complex setups, use something like pureData/max msp/touchDesigner to interpret and manipulate the OSC data and then send to VCV.

It also works the other way around if you want to control other software with cv from VCV at a default rate of 100hz per channel. Clock the "TRG" input for a custom update rate.

**Comment by nesdnuma** [comment]
Following your explanations I could route every data where it was supposed to go. However I have some "staircase" effect (jumps between values). Could it be that the module has a limited sample rate on the OSC->cv?

**Comment by j4s0n-c** [comment]
@nesdnuma The absolute limit is the engine sample rate, your network bandwidth, or overall performance of the computer. If you are seeing the jumps on a scope, that could also be limited by the framerate of the GUI (set in VCV menu, View, Frame rate. Maximum is whatever your monitor can handle) If you are hearing  jumps in values that could be limited by audio sample rate, network bandwidth, or the application you are sending OSC from. You could try a slew limiter module to smooth out the values.
