### ISSUE TITLE
[linux] [cvOSCcv] Have to click some buttons twice

### ISSUE THREAD

**Issue by jamshark70** [j4s0n-c/trowaSoft-VCV#53]
1. Add a cvOSCcv module into a patch.
2. Click "config" to edit.
3. Click an "adv" button.
4. Cancel the adv editor.

At step 3 (sometimes), and step 4 (pretty much all the time), the first mouse click doesn't do anything, but the second click does.

I don't see a good reason why it should be necessary to click twice, so I assume it's a bug.

Ubuntu Studio 20.04 with XFCE desktop. Standard VCV Rack installation package.

**Comment by j4s0n-c** [comment]
It is a bug that we are aware of. Thanks for reporting. We'll try to sort it out ASAP.
