### ISSUE TITLE
Rack V2 ?

### ISSUE THREAD

**Issue by Stubs42** [j4s0n-c/trowaSoft-VCV#54]
Hi,
is there any approach for porting to Rack Version 2 ?
If so, will you include the patch I suggested in my Issue 'Easy patch to drastically reduce CPU overhead of trigSeq(64) and and voldSeq' ?
Regards
Dieter (OrangeLine)

**Comment by chichian** [comment]
Hi Dieter,

Sorry we have been busy. Yes, I had integrated your patch but we were still testing it to make sure it didn't interfere with anything else (but that was v1 framework). 

We will be porting to v2 and the intent is to include your patch. Thanks.

**Comment by dmitru** [comment]
Really looking forward to a v2 version! Keep up the great work

**Comment by Stubs42** [comment]
Yes please, since I desperately need the voltseq and trig seg sequencers because there is no alternative if you want to have patterns and 16 channels. Nearly all my sequencer templates and patches use them and they work perfectly with my OrangeLine PHRASE module to make them play phrases longer than 16 steps and utilize a master sequencer sequencer to setup whole songs. 
Here are some features which would be great also but AFTER the first release in V2.
* Length per channel
* Polyphonic clock input to drive each channel separately
* Polyphonic channel output

**Comment by Outboarder** [comment]
The best sequencer in vcv, I really need this specially for OSC.
Hope we get this soon.

**Comment by nesdnuma** [comment]
Hello, any release date planned for cvOSCcv and its expanders in the Rack 2.x version?

**Comment by j4s0n-c** [comment]
@nesdnuma It's available [here](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v2.0.4-alpha) on github. We'll submit to the library when the new modules are done and everything is fully tested.
