### ISSUE TITLE
Only the first expander has its channels auto-incremented

### ISSUE THREAD

**Issue by jpnielsen** [j4s0n-c/trowaSoft-VCV#56]
Version 2.0.4-alpha on Rack 2.0.4 free.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/27916597/147405015-07b514d6-7644-4c6a-87c2-e28461133e19.png">

<img width="334" alt="image" src="https://user-images.githubusercontent.com/27916597/147405051-ce2bfbae-b3c9-44be-a4f1-935cfc0fbe20.png">

The first expander is correctly numbered /ch/9 to /ch/16
The second expander is in-correctly numbered /ch/9 to /ch/16 - should be /ch/17 to /ch/24
The same results on left or right expanders.
Third, Fourth expanders also start channel naming at /ch/9.

**Comment by chichian** [comment]
Hi jpnielsen,

Yeah, I see how that is confusing. An expander starts /ch/9 when created before it knows where it is or if it even has a master yet. **The expander will then only re-address if you initialize it**. I didn't want to accidentally clobber user addresses if you were just moving them around and re-ordering them (or moving them to different cvOSCcv). I had actually done this to myself when I initially made the expanders and was testing them w/automatic readdressing (overwrote all my addresses that I was using when I moved it to another cvOSCcv), so we force the user to intentionally re-address.

So if you want them to auto-address numerically, after putting any subsequent expanders down (with a master found), then right click on it and click on Initialize from the context menu (or CTRL-I).

This should have been the behavior in v1 too. I didn't change any of this part...

**Comment by jpnielsen** [comment]
Thank you.

It's in the Fine Manual even:

"By default, channels start at #9. After connecting to a master cvOSCcv module, initializing the expansion module will "re-number" its channels (i.e. /ch/9 will become /ch/17)."

Sorry about that.

**Comment by chichian** [comment]
Actually it's good you brought this up. This made me notice that it doesn't rename the advanced configuration screen (it still says configuring /ch/9) when you load from a save, since I wasn't saving the channel numbers in the save file (just the addresses), so I am fixing that. This wouldn't break your OSC since the addresses are the important part, but it should be consistent in the labelling.
