### ISSUE TITLE
TrigSeq64 short freezes.

### ISSUE THREAD

**Issue by Nightquaker** [j4s0n-c/trowaSoft-VCV#6]
Hello there!
I'm new to the GitHub stuff, but I guess I can report a bug here.
TrigSeq64 has minor freezes on my VCVrack (0.5.0). The freezes might even cause desynchronization.
Here's an example of freezes: https://www.youtube.com/watch?v=AaQvU101Bzs with desynchronization happening about 30 seconds in.
It's a fairly simple patch, so my CPU can handle it just fine, and the freezes happen specifically when TrigSeq64 is in the patch.
Happens with both ASIO and DirectSound, so ASIO is not the issue.
Thank you!

**Comment by chichian** [comment]
Hi Nightquaker. Could you post the patch file?

**Comment by Nightquaker** [comment]
Here it is!
http://www.mediafire.com/file/85l9boi1b3sh9s2/Modular%20march%206.vcv

**Comment by j4s0n-c** [comment]
Sorry for the delay. I am unable to replicate the issue on this end. I do not have the Vult modules to test with but I replaced those with a kick and snare from Autodafe Drum kit and did not experience any hiccups (in VCV Rack version 0.5.1). Does it still happen if you are not recording the screen and audio? I've heard that turning off wifi can help eliminate lags.  What are your hardware specs and operating system?

**Comment by Nightquaker** [comment]
The delay is no problem.
My OS is WIndows 8.
The specs are:
Phenom X3 8450 at 2.1 GHz
HD6850
6 gigs of RAM.

I just tried TrigSeq with Autodafe Drum Kit and there are hiccups on my end.
It could very well be related to my CPU, to be honest. As you might imagine, it is not very fast.
I don't use WiFi, so there's no problem in that regard.
I will do some more testing without Vult modules later today and will report the results here.

**Comment by j4s0n-c** [comment]
I am having some strange timing issues on OSX with multiple sequencers loaded and running, but no issue on windows. We may have to design an "eco" mode for better performance with less visual feedback, etc.. But I don't think this can really be called a bug.

**Comment by Nightquaker** [comment]
Are the timing issues similar (in their symptoms) to the short freezes I mentioned?
Sorry, I'm not technically proficient with VCVrack, so I can't really differentiate those issues myself.

**Comment by Nightquaker** [comment]
Was using TrigSeq yesterday and confirmed short freezes regardless of connected to it modules.
Might update to Rack 0.6 soon and test it out there.

**Comment by Nightquaker** [comment]
Just did some patching with TrigSeq in 0.6 and didn't notice any short freezes so far.

**Comment by j4s0n-c** [comment]
That's great to hear. The performance of Rack seems to vary quite a bit across our available hardware and even operating systems on the same hardware. And obviously, there are improvements being made to rack itself all the time. I guess you could say the modules can only be as efficient as the engine allows. Shall we close this issue?

**Comment by Nightquaker** [comment]
Yes, the issue can be closed.
Thank you very much for the support and for making great modules!
