### ISSUE TITLE
Explain handling of polyphony when cvOSCcv receives messages

### ISSUE THREAD

**Issue by nesdnuma** [j4s0n-c/trowaSoft-VCV#61]
Hello, 

It is unclear to me how cvOSCcv uses the polyphony when receiving OSC messages. Can one manage the target voice according to the OSC message transmitted from the outside to the module or will the module go from voice to voice in a round robin fashion everytime a new trigger is provided?

**Comment by j4s0n-c** [comment]
Each channel can receive up to 16 values packed into an array. OSC addresses for each channel can be changed in config. All values in a channel are updated anytime an OSC message is received. Use a VCV Split module to access each value individually.
![TDarray_to_cvOSCcv](https://user-images.githubusercontent.com/4063528/171311030-90516dad-953b-4c77-aa42-699d5196a72c.jpg)
