### ISSUE TITLE
Compilation error v2

### ISSUE THREAD

**Issue by nielszweistein** [j4s0n-c/trowaSoft-VCV#62]
src/TSTextField.cpp:11:1: note: « std::ostream_iterator » est défini dans l'en-tête « <iterator> » ; avez-vous oublié « #include <iterator> » ?
   10 | #include "trowaSoftComponents.hpp"
  +++ |+#include <iterator>

Adding `#include <iterator> `  in  src/TSTextField.cpp  is working

Thx @j4sOn-c for your modules !

**Comment by nielszweistein** [comment]
missing part in the previous message

Adding     
#include <iterator>      
in src/TSTextField.cpp is working

**Comment by chichian** [comment]
Merci. I did not realize that this wasn't compiling... Linux I assume? I think we've only been compiling on Windows and Mac. I have added the include.

**Comment by nielszweistein** [comment]
Yes, it was for "Linux" platform.
thank you
