### ISSUE TITLE
v2 version stores font references across fonts

### ISSUE THREAD

**Issue by cschol** [j4s0n-c/trowaSoft-VCV#65]
Storing font references across frames crashes the Rack VST.

See the Rack [migration manual](https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames) for more information on how to resolve this issue.

**Comment by chichian** [comment]
Hi cschol. Is there an easy way to test/debug the VST version? I am at the point where it does not crash Ableton but when you close and reload the VST, the fonts are gone on subsequent openings. I am loading the pointers right before relevant draw calls (i.e. in like draw() or drawLayer()), so I don't know why this is happening.

I do not have Pro or a DAW for that matter, so I have to have j4s0n load the new dll and test each time I make a change. It would be easier if there was a debug build or tool that I could use and I could maybe print to DEBUG log or step into the code.

**Comment by chichian** [comment]
Nevermind. j4s0n was grabbing an old dll.
