### ISSUE TITLE
multiSeq Display of Note in NOTE mode is not showing correct note

### ISSUE THREAD

**Issue by Stubs42** [j4s0n-c/trowaSoft-VCV#66]
In NOTE mode multiseq does not show the correct note in the display.
For example G4 is displayed as D5

**Comment by chichian** [comment]
Hmm. Let me look at that. It used to work in v1 (we never released it though but it was written a long time ago).  But I see now it somehow got messed up in the v2 conversion.

**Comment by chichian** [comment]
Hi. This has been fixed in the latest [release v2.0.6](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v2.0.6) and should update in the library in the next week or so.
