### ISSUE TITLE
Not sure which IP to use when receiving message from another device on the same wifi network

### ISSUE THREAD

**Issue by NNNenov** [j4s0n-c/trowaSoft-VCV#69]
ello, I'm trying to send an OSC message to the cvOSCcv module from a microcontroller over the same wifi network. The connection seems to be working fine with MaxMSP udpreceive, I'm able to send float messages to it. But with vcv rack 2 I'm not sure how to get the cvOSCcv module to pick it up. I tried setting the IP to 127.0.0.1 and also tried the IPv4 of my machine, the message is formatted "/ch/1" " value" value being 0. to 1.

I am realising the IP address may only be relevant for outgoing messages from VCV rack, for incoming I would assume it is not used, or should stay at the default 127.0.0.1 so my issue is maybe related to message syntax, but I don't know, I couldn't tell from the documentation in the manual.

For further debugging, I tried sending OSC internally (on same machine) from max msp to vcv rack 2 cvOSCcv module, targeting 127.0.0.1 with In Port 7375:
sending value 0.5, the message is formatted "/ch/1 0.5"
cvOSCcv received a trigger message, but VAL stays at 0

I then tried sending OSC from cvOSCcv to max msp, the message is received and formatted the same, "/ch/1 0.5"
So it seems that when formatting my message in the same way, only a trigger is received, and I'm not sure why nothing is received when trying to send osc from a device on same network.

**Comment by NNNenov** [comment]
For debugging, I tried sending OSC internally from max msp to vcv rack 2 cvOSCcv module, targetting 127.0.0.1 with In Port 7375:
sending value 0.5, the message is formatted "/ch/1 0.5" 
cvOSCcv recieves a trigger message, but VAL stays at 0

I then tried sending OSC from cvOSCcv to max msp, the message is recieved and formatted the same, "/ch/1 0.5"
So i'm not sure when formatting my message the same only a trigger is received, and why nothing is recieved when trying to send osc from a device on same network.

**Comment by NNNenov** [comment]
I have done further debugging and found that packing the message "/ch/1 f" f being some float value, is working correctly, I wasn't packing it properly in max msp.
However, i still dont get any signal when sending a message with the same formatting from my microcontroller over wifi network. I even copied the print result which was received in max msp from the microcontroller over wifi and sent it to vcv rack, and it worked, so im really stuck now.

**Comment by NNNenov** [comment]
the issue was my firewall blocking vcv rack, apologies

**Comment by j4s0n-c** [comment]
@NNNenov I was working on a detailed reply yesterday, but saw that you were working it out on your own. Basically, I was thinking the values need to be typed as float, int, or bool, can't be strings. And that maybe there was a networking issue. Glad you got it sorted out. Enjoy!
