### ISSUE TITLE
Tweak TrigSeq's

### ISSUE THREAD

**Issue by Coirt** [j4s0n-c/trowaSoft-VCV#7]
I'll link the git, maybe it is something you know how to do yourself! 

https://github.com/VCVRack/Rack/issues/607#issuecomment-356457786

**Comment by chichian** [comment]
Hi LKHSogpit.  That is a nice idea. We can try.  No promises though.

**Comment by Coirt** [comment]
Cool.

**Comment by chichian** [comment]
Hi Coirt(?). 

I added this in the [0.5.5.2 release](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v0.5.5.2). Please check it out and let me know if it's OK. Hopefully no bugs.

Thanks for the suggestion!

**Comment by Coirt** [comment]
Hi yes, works okay. Will get a chance tomorrow to properly test and let you know if I find anything.
