### ISSUE TITLE
Crashes Rack on Mac ARM64

### ISSUE THREAD

**Issue by chichian** [j4s0n-c/trowaSoft-VCV#73]
Andrew reported at library:

https://github.com/VCVRack/library/issues/441#issuecomment-1685147911

> This crashes Rack on Mac ARM64 with
> 
> ```
> Assertion failed: (sizeof(osc::int32) == 4), function OutboundPacketStream, file lib/oscpack/osc/OscOutboundPacketStream.cpp, line 167.
> ```
> 
> when instantiating any modules.

**Comment by cschol** [comment]
Crash is resolved on `arm64` with latest changes, but #74 requires some more adjustments to make the build work on the `arm64` platform. This issue can be closed.
