### ISSUE TITLE
Base pitch in voltSeq (note mode)

### ISSUE THREAD

**Issue by MarcBoule** [j4s0n-c/trowaSoft-VCV#9]
Hi, if I understand Rack's voltage standards correctly, could it be possible that the notes displayed in the buttons in the voltSeq sequencer, in note mode, are off by one volt? For example, when setting a button to the C4 note, the output is -1V instead of 0V. From the doc:
"If you need a default pitch for your oscillator with initial knob positions and 0V at the pitch input, use C4 (f0 = 261.626 Hz)."
https://vcvrack.com/manual/VoltageStandards.html
Not sure if my point is valid, but I get the impression all voltages output by the sequencer should be shifted up by 1V. Apologies if I misunderstood something. Thanks!

**Comment by chichian** [comment]
Hi Marc,

Oops. You may be correct. This is probably my fault. I didn't think there was a standard other than C's were even voltages, so I went -5 to +5 V (symmetry is always nice and I know nothing about music).

Let us look into this and how I can change it and hopefully gracefully deal with previous saves with a conversion to -4 to +6V.

**Comment by MarcBoule** [comment]
Thanks for the followup. If ever there is no graceful way to make the change, perhaps waiting until the change to Rack v.0.6 would be best, to synchronize with that more major event. Cheers!

**Comment by chichian** [comment]
Hi Marc,

I've changed it in this [0.5.5.2 release](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v0.5.5.2).  The 'notes' should be the same as what was displayed to the user before, but the voltages will be +1 more. I've added a "Shift" voltages in the context menu to compensate for this (in case the users actually wanted the old voltages).

Thanks for catching that!

**Comment by MarcBoule** [comment]
Awesome! The new options are actually a cool new feature also, and would find use in other cases as well I imagine. Thanks for the fix, and your sequencers are superb by the way! 👍
